### ISSUE TITLE
核心非uid:0状态下测速出错

### ISSUE THREAD

**Issue by x4455** [x4455/smartdns-Android#1]
在还在测试的新版中，核心以非uid:0状态运行时会被如下报错刷爆log
```
[2019-10-21 09:53:24,066][ERROR][      fast_ping.c:566 ] create icmp socket failed, Operation not permitted
```
@pymumu

**Comment by pymumu** [comment]
ping的话需要root权限，没有root权限只能用tcp来测速，能支持设置测速模式的程序还没正式发布
先看看这里能不能用(临时路径）
https://github.com/pymumu/smartdns/releases/download/untagged-68e898f78aff922d8541/smartdns-aarch64

https://github.com/pymumu/smartdns/releases/download/untagged-68e898f78aff922d8541/smartdns.1.2019.10.20-1735.aarch64-debian-all.deb

配置参数，可以参考.deb包里面的conf文件，或.deb里面的readme

speed-check-mode tcp:80

**Comment by x4455** [comment]
> ping的话需要root权限，没有root权限只能用tcp来测速，能支持设置测速模式的程序还没正式发布
> 先看看这里能不能用（临时路径）
> [https://github.com/pymumu/smartdns/版本/下载/未标记-68e898f78aff922d8541 / smartdns-aarch64](https://github.com/pymumu/smartdns/releases/download/untagged-68e898f78aff922d8541/smartdns-aarch64)
> 
> https://github.com/pymumu/smartdns/releases/download/untagged-68e898f78aff922d8541/smartdns.1.2019.10.20-1735.aarch64-debian-all.deb
> 
> 配置参数，可以参考.deb包里面的conf文件，或.deb里面的自述文件
> 
> 速度检查模式tcp：80
这两链接用不了乁( •_• )ㄏ

**Comment by pymumu** [comment]
[smartdns.1.2019.10.20-1735.aarch64-debian-all.deb.zip](https://github.com/x4455/smartdns-Android/files/3751413/smartdns.1.2019.10.20-1735.aarch64-debian-all.deb.zip)

**Comment by x4455** [comment]
@pymumu 改成tcp测试确实没有那些报错了 :smiley: 新版什么时候放出来啊
如果把手机用来给局域网内做服务器，bind该怎么填啊
