### ISSUE TITLE
这个怎么安装在andriid上呢？

### ISSUE THREAD

**Issue by sensen1** [x4455/smartdns-Android#2]
是需要自己编译成arm框架的 apk然后安装吗？
还是 需要什么命令行模拟器 然后源码方式安装呢？
能否可能出个云编译的Workflow文件呢？

**Comment by x4455** [comment]
这是个magisk模块，需要安装有magisk框架的手机。下载zip刷入，配置文件后重启即可。
使用终端模拟器获取su，输入命令就能控制。
~~最新发布版那个发现有安装bug就撤了~~
编译方面我也是个新手，我自己也尝试过去编译，不过运行不了

**Comment by sensen1** [comment]
> 这是个magisk模块，需要安装有magisk框架的手机。下载zip刷入，配置文件后重启即可。
> 使用终端模拟器获取su，输入命令就能控制。
> ~最新发布版那个发现有安装bug就撤了~
> 编译方面我也是个新手，我自己也尝试过去编译，不过运行不了

非常感谢回复，有谱了。 那我了解了。 顺便问一下，这个的开发目的是用于，手机端临时开启一个smartdns作为server，然后能提供给网内的其他人吗？ 类似自用或者旁路由？

**Comment by x4455** [comment]
默认仅给本地提供服务，要给其他设备使用的话，执行 `smartdns -mode proxy` 切换至代理模式，向本机发送的53数据包会被重定向到 Route_PORT 。

`~ --strict [true/false]` 控制来源IP限制，默认true，只有来源IP是 ```10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fec0::/10``` 的数据包才会转发到 Route_PORT

- 但目前还未使用封锁策略，所以仍然可以通过指定端口的方式使用。

`~ -mode server` 时仅运行服务，不动 iptables ，你可以在smartdns配置中直接指定53端口。

**Comment by sensen1** [comment]
> 默认仅给本地提供服务，要给其他设备使用的话，执行 `smartdns -mode proxy` 切换至代理模式，向本机发送的53数据包会被重定向到 Route_PORT 。
> 
> `~ --strict [true/false]` 控制来源IP限制，默认true，只有来源IP是 ```10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fec0::/10``` 的数据包才会转发到 Route_PORT
> 
> - 但目前还未使用封锁策略，所以仍然可以通过指定端口的方式使用。
> 
> `~ -mode server` 时仅运行服务，不动 iptables ，你可以在smartdns配置中直接指定53端口。

感谢 已经了解了 。
