### ISSUE TITLE
已经刷入最新，status也显示启动。但是nslookup还是显示运营商的dns

### ISSUE THREAD

**Issue by jorismq** [x4455/smartdns-Android#7]
我添加了上游的DNS

**Comment by jorismq** [comment]
按照配置参数都改了，就是把字段前面的#删掉了，还是没用
请大神出个详细的教程啊

**Comment by x4455** [comment]
由于使用iptables方法重定向，所作的更改很难在明面上看到。

如果你不确定是否生效。请打开审计，即 `audit-enable yes` 。如果正常工作，则应在相应的日志中看到类似 `127.0.0.1 query` 的字段。

**Comment by jorismq** [comment]
打开了但是没有相应的log
只有/dev/smartdns/config/log/smartdns.log
里面倒是显示add server 8。8。4。4：853 type：tls之类的
不知道对不对

**Comment by x4455** [comment]
最简单的测试方法：使用address规则解析一个域名。
nslookup能解析到对应的结果即为有效。(注意不能使用root权限执行nslookup)

**Comment by jorismq** [comment]
> 最简单的测试方法：使用address规则解析一个域名。
> nslookup能解析到对应的结果即为有效。(注意不能使用root权限执行nslookup)

"不能使用root权限执行nslookup"应该是正解
直接nslookup，现在server名是8。8。8。8了
感谢！

**Comment by x4455** [comment]
以变量 ServerUID 和 pkg 中的 uid 所发出的查询，不受重定向影响。

**Comment by AngusLkc** [comment]
经验表明：重定向本机发出的udp包需在mangle表打标签再结合ip rule使流量重新进入协议栈并在prerouting链上匹配到后再redirect到6053端口才能起作用。
