### ISSUE TITLE
开启以后，安卓手机的“屏幕投屏（screen cast）”功能无效了。关闭服务后正常

### ISSUE THREAD

**Issue by jorismq** [x4455/smartdns-Android#8]
手机和网络设置没问题
只要关了smartdns就能正常

**Comment by x4455** [comment]
没用过这个功能。可能通过域名解析获取其在局域网中的IP，一般是由局域网中的DNS进行解析。

建议使用抓包软件，或者开启解析日志查找可能相关的解析记录。

解决方案

在 smartdns.conf 中配置相关解析。
- 方法1：用address直接配置静态
- 方法2：创建一个server指向路由器IP并指定group，用nameserver把相关域名解析到对应group

或者把相关的 应用包名 写入到 script.conf 中的 pkg 中，直接放行整个应用。

**Comment by jorismq** [comment]
安卓手机的热点功能也不能开了
或者要反复点“开”6-7次才可能打开一次

**Comment by jorismq** [comment]
> 没用过这个功能。可能通过域名解析获取其在局域网中的IP，一般是由局域网中的DNS进行解析。
> 
> 建议使用抓包软件，或者开启解析日志查找可能相关的解析记录。
> 
> 解决方案
> 
> 在 smartdns.conf 中配置相关解析。
> 
> * 方法1：用address直接配置静态
> * 方法2：创建一个server指向路由器IP并指定group，用nameserver把相关域名解析到对应group
> 
> 或者把相关的 应用包名 写入到 script.conf 中的 pkg 中，直接放行整个应用。

我找到了那个应用包名，应该是com.qualcomm.wfd.service，请问具体怎么放行

**Comment by x4455** [comment]
> 我找到了那个应用包名，应该是com.qualcomm.wfd.service，请问具体怎么放行

请参照readme文件，对 `脚本配置文件` 中的 `pkg` 进行修改

**Comment by jorismq** [comment]
> > 我找到了那个应用包名，应该是com.qualcomm.wfd.service，请问具体怎么放行
> 
> 请参照readme文件，对 `脚本配置文件` 中的 `pkg` 进行修改

谢谢，我放行了，准备试试。
请教一下，“热点”功能无法打开的问题怎么解决啊？
“热点”应用包我也放行了，但是还是要反复点“开关”很多次才可能成功打开一次。。。
log里面也没见有什么提示

**Comment by x4455** [comment]
> 请教一下，“热点”功能无法打开的问题怎么解决啊？
> “热点”应用包我也放行了，但是还是要反复点“开关”很多次才可能成功打开一次。。。
> log里面也没见有什么提示

你用的是什么工作模式， local 还是 proxy。

考虑到使用了iptables，你可以给我看看iptables规则有没有出问题

按照以下

- 禁用smartdns模块时，开启热点后、关闭热点后
- 启用smart时，第一次点开启热点后、热点成功开启后和关闭热点后

用以下操作获取规则
终端获取root后，输入`iptables -t nat -S >> /sdcard/debug_log.txt`
在内部存储下找到这个文件，每次获取完把文件**改好名字**。最好能让我分辨清楚

**Comment by jorismq** [comment]
谢谢

[新建文件夹 (2).zip](https://github.com/x4455/smartdns-Android/files/5903436/2.zip)

**Comment by jorismq** [comment]
谢谢
模式是默认的，script.conf里面显示  mode='L'
我也对比了下，发现开启smartdns的都分别多了这句话
用wifi的-A tetherctrl_nat_POSTROUTING -o wlan0 -j MASQUERADE
用流量的-A tetherctrl_nat_POSTROUTING -o rmnet_data1 -j MASQUERADE

**Comment by jorismq** [comment]
谢谢
模式是默认的，script.conf里面显示  mode='L'
我也对比了下，发现开启smartdns后能够稳定使用的状态都分别多了这句话
用wifi的-A tetherctrl_nat_POSTROUTING -o wlan0 -j MASQUERADE
用流量的-A tetherctrl_nat_POSTROUTING -o rmnet_data1 -j MASQUERADE

**Comment by x4455** [comment]
> 模式是默认的，script.conf里面显示 mode='L'
> 我也对比了下，发现开启smartdns后能够稳定使用的状态都分别多了这句话
> 用wifi的-A tetherctrl_nat_POSTROUTING -o wlan0 -j MASQUERADE
> 用流量的-A tetherctrl_nat_POSTROUTING -o rmnet_data1 -j MASQUERADE

暂时想不出是什么问题，等新版吧。改了不少东西。
